Repository yearn/yearn-comms, pull requests merged in 2021-11, with the labels that each got.

#497 [CMT-170] Introducing Fixed Forex - TR
  Articles/_posts/Medium/Andre Cronje/Introducing Fixed Forex/2021-07-02-Introducing-Fixed-Forex.md
Labels: Turkish

#605 [CMT-52] That's boost folks
  Articles/_posts/Medium/Yearn.Finance/yvBOOST/2021-09-14-thats-boost-folks.md
Labels: Chinese

#496 [CMT-115] Decentralized Payroll Management for DAOs - TR
  Articles/_posts/Medium/Andre Cronje/Decentralized Payroll Management for DAOs/2021-03-31-Decentralized-Payroll-Management-for-DAOs.md
Labels: Turkish

#580 [CMT-434] - What is Yearn - TR
  Tweets/_posts/What is Yearn/2021-10-09-What-is-Yearn.md
Labels: Turkish

#578 [CMT-79] - Easily earn with Yearn v2 in Argent
  Articles/_posts/Argent/2021-08-24-easily-earn-with-yearn-v2-in-argent.md
Labels: Portuguese

#581 [CMT-412] Tweet - Bowswap.Finance - TR
  Tweets/_posts/Bowswap.finance/2021-09-10-bowswapfinance.md
Labels: Turkish

#582 [CMT-368] Tweet - Claim from old yGov - TR
  Tweets/_posts/Claim from old ygov/2021-07-10-Claim-from-old-ygov.md
Labels: Turkish

#601 [CMT-417] Tweet - Transparency Summary #557 German
  Tweets/_posts/Transparency Summary/2021-10-05-TransparencySummary.md
Labels: German

#584 [CMT-401] Tweet - Atlantis World Grant - TR
  Tweets/_posts/Yearn grant Atlantis World/2021-08-31-Yearn-grant-Atlantis-World.md
Labels: Turkish

#620 [CMT-157] - Yearn Finance - Dec Asset Management
  Articles/_posts/SEBA Bank/Yearn-Finance-Decentralised-Asset-Management/2021-06-02-Yearn-Finance-Decentralised-Asset-Management.md
Labels: Portuguese

#585 [CMT-366] - Claim from old yGov
  Tweets/_posts/Claim from old ygov/2021-07-10-Claim-from-old-ygov.md
Labels: Portuguese

#583 [CMT-423] Tweet - Transparency Summary - TR
  Tweets/_posts/Transparency Summary/2021-10-05-TransparencySummary.md
Labels: Turkish

#599 [CMT-406] Tweet - Bowswap.Finance #548 German
  Tweets/_posts/Bowswap.finance/2021-09-10-bowswapfinance.md
Labels: German

#616 [CMT-362] Tweet - Claim from old yGov #509 German
  Tweets/_posts/Claim from old ygov/2021-07-10-Claim-from-old-ygov.md
Labels: German

#617 [CMT-351] Tweet - What is a DAO? #500 German
  Tweets/_posts/What is a DAO/2021-06-30-What-is-a-DAO.md
Labels: German

#594 [CMT-190] - Article - The Blue Pill
  Articles/_posts/The Blue Pill/The Blue Pill.txt
Labels: Portuguese

#592 [CMT-432] - Tweet - What is Yearn?
  Tweets/_posts/What is Yearn/2021-10-09-What-is-Yearn.md
Labels: Portuguese

#593 [CMT-421] - Tweet - Transparency Summary
  Tweets/_posts/Transparency Summary/2021-10-05-TransparencySummary.md
Labels: Portuguese, translation check

#606 Greek Translation - Yearn Finance Newsletter #41
  Newsletters/_posts/Yearn-Finance-Newsletter-41/2021-07-20-Yearn-Finance-Newsletter-41.md
Labels: Greek

#614 Yearn Finance Newsletter #42 Greek Translation
  Newsletters/_posts/Yearn-Finance-Newsletter-42/2021-08-03-Yearn-Finance-Newsletter-42.md
Labels: Greek

#646 add YN #49
  Newsletters/_posts/Yearn-Finance-Newsletter-49/2021-11-14-Yearn-Finance-Newsletter-49.md
  Newsletters/_posts/Yearn-Finance-Newsletter-49/image1.png
  Newsletters/_posts/Yearn-Finance-Newsletter-49/image2.png
  Newsletters/_posts/Yearn-Finance-Newsletter-49/image3.png
  Newsletters/_posts/Yearn-Finance-Newsletter-49/image4.png
  Newsletters/_posts/Yearn-Finance-Newsletter-49/image5.png
  Newsletters/_posts/Yearn-Finance-Newsletter-49/image6.png
  Newsletters/_posts/Yearn-Finance-Newsletter-49/image7.png
  Newsletters/_posts/Yearn-Finance-Newsletter-49/image8.png
Labels: English

#635 [CMT-250] - Announcements - Zero Knowledge Podcast
  Annoucements/_posts/Zero Knowledge Podcast/2021-05-05-Zero-Knowledge-Podcast.md
Labels: needs review by translator

#644 [CMT-355] - DAO
  Tweets/_posts/What is a DAO/2021-06-30-What-is-a-DAO.md
Labels: needs review by translator

#609 [CMT-384]- Risk, Tooling & Insight #529 German
  Tweets/_posts/Risk, Tooling, & Insight/2021-08-12-Risk,-Tooling,-&-Insight.md
Labels: German, translation check

#629 [CMT-372] Tweet - Bear market, bullish development #518 FRENCH
  Tweets/_posts/Bear market, bullish development/2021-07-22-Bear-market,-bullish-development.md
Labels: needs review by translator

#280 [CMT-41] Q2 Financial Report_VI
  Financials/_posts/Quarterly-Report/2021-Q2/2021-09-11-2021-Q2.md
  Financials/_posts/Quarterly-Report/2021-Q2/image2_vn.png
Labels: Vietnamese

#655 [CMT-387] translation(tweet): risk, tooling, & insignt
  Tweets/_posts/Risk, Tooling, & Insight/2021-08-12-Risk,-Tooling,-&-Insight.md
Labels: needs review by translator

#638 [CMT-305] - Prop Fund Builder First Legal Act DAO
  Annoucements/_posts/Legal-Activism-DAO/2021-08-03-Legal-Activism-DAO.md
Labels: needs review by translator

#627 [CMT-301] Ann - First Legal Activism DAO #458 German
  Annoucements/_posts/Legal-Activism-DAO/2021-08-03-Legal-Activism-DAO.md
Labels: needs review by translator

#664 [CMT-415] Transparency summary Translated to Chinese
  Tweets/_posts/Transparency Summary/2021-10-05-TransparencySummary.md
Labels: needs review by translator

#623 [CMT-334] Ann - YFIStats Dashboards #485 German
  Annoucements/_posts/Updated YFIStats Dashboards/2021-09-30-Updated-YFIStats-Dashboards.md
Labels: needs review by translator

#666 [CMT-393] Atlantis World Grant Translated to Chinese
  Tweets/_posts/Yearn grant Atlantis World/2021-08-31-Yearn-grant-Atlantis-World.md
Labels: needs review by translator

#665 [CMT-404] Bowswap Finance Translated to Chinese
  Tweets/_posts/Bowswap.finance/2021-09-10-bowswapfinance.md
Labels: needs review by translator

#626 [CMT-312] Ann - Blue Pill Release #467 German
  Annoucements/_posts/The Blue Pill Release/2021-08-03-Blue-Pill-Release.md
Labels: needs review by translator

#625 [CMT-290] Anno - The Blue Pill Ann. #450 German
  Annoucements/_posts/The Blue Pill Ann/2021-07-30-The-Blue-Pill-Ann.md
Labels: needs review by translator

#624 [CMT-323] Ann - Update Bowswap #476 German
  Annoucements/_posts/Update Bowswap.Finance/2021-08-26-Update-Bowswap.Finance.md
Labels: needs review by translator

#284 [CMT-433] What-Is-Yearn-Updated
  Tweets/_posts/What is Yearn/2021-10-09-What-is-Yearn.md
Labels: translation check, Spanish

#285 [CMT-240] Update 2021-09-11-2021-Q2.md
  Financials/_posts/Quarterly-Report/2021-Q2/2021-09-11-2021-Q2.md
Labels: translation check, Spanish

#286 [CMT-378] Update to Bear-market,-bullish-development.md
  Tweets/_posts/Bear market, bullish development/2021-07-22-Bear-market,-bullish-development.md
Labels: translation check, Spanish

#287 [CMT-328] Update 2021-09-10-bowswapfinance.md
  Tweets/_posts/Bowswap.finance/2021-09-10-bowswapfinance.md
Labels: translation check, Spanish
