Repository yearn/yearn-comms, pull requests merged in 2022-11, with the labels that each got.

#1509 add(French): Tout savoir sur le yCRV (article/doc)
  public/_posts/_articles/yearn-finance/yCRV/cover.jpg
  public/_posts/_articles/yearn-finance/yCRV/fr.md
  public/_posts/_articles/yearn-finance/yCRV/image1.jpg
  public/_posts/_articles/yearn-finance/yCRV/image2.jpg
  public/_posts/_articles/yearn-finance/yCRV/image3.jpg
  public/_posts/_articles/yearn-finance/yCRV/image4.jpg
  public/_posts/_articles/yearn-finance/yCRV/image5.jpg
  public/_posts/_articles/yearn-finance/yCRV/image6.jpg
  public/_posts/_articles/yearn-finance/yCRV/image7.jpg
Labels: French

#1513 add(english): yearn-cowswap (article)
  public/_posts/_articles/yearn-finance/cowswap/cover.jpg
  public/_posts/_articles/yearn-finance/cowswap/en.md
  public/_posts/_articles/yearn-finance/cowswap/image1.jpg
Labels: English

#1515 add(english): yearnv3-motivation-and-design (article)
  public/_posts/_articles/yearn-finance/yearn-v3/en.md
  public/_posts/_articles/yearn-finance/yearn-v3/image1.jpg
  public/_posts/_articles/yearn-finance/yearn-v3/image2.jpg
  public/_posts/_articles/yearn-finance/yearn-v3/image3.jpg
Labels: English

#1516 update: change banner/featured to yearn-v3
  public/_posts/_articles/yearn-finance/yearn-v3/cover.png
  public/_posts/featured.md
Labels: blog

#1522 add(english): Introducing Yearn’s new bribe platform for Curve gauge voting (article)
  public/_posts/_articles/farrahmay/ybribe/cover.jpg
  public/_posts/_articles/farrahmay/ybribe/en.md
  public/_posts/_articles/farrahmay/ybribe/image1.jpg
  public/_posts/_articles/farrahmay/ybribe/image2.jpg
  public/_posts/_articles/farrahmay/ybribe/image3.jpg
  public/_posts/_articles/farrahmay/ybribe/image4.jpg
  public/_posts/_articles/farrahmay/ybribe/image5.jpg
  public/_posts/_articles/farrahmay/ybribe/image6.jpg
  public/_posts/_articles/farrahmay/ybribe/image7.jpg
  public/_posts/_articles/farrahmay/ybribe/image8.jpg
  public/_posts/_articles/farrahmay/ybribe/image9.jpg
Labels: English
