Repository yearn/yearn-comms, pull requests merged in 2022-04, with the labels that each got.

#1235 add(article): Self-Hosting Web3 Services - EN
  public/_posts/_articles/marco-worms/self-hosting/en.md
  public/_posts/_articles/marco-worms/self-hosting/image1.jpg
  public/_posts/_articles/marco-worms/self-hosting/image10.jpg
  public/_posts/_articles/marco-worms/self-hosting/image11.jpg
  public/_posts/_articles/marco-worms/self-hosting/image12.jpg
  public/_posts/_articles/marco-worms/self-hosting/image13.jpg
  public/_posts/_articles/marco-worms/self-hosting/image2.jpg
  public/_posts/_articles/marco-worms/self-hosting/image3.jpg
  public/_posts/_articles/marco-worms/self-hosting/image4.jpg
  public/_posts/_articles/marco-worms/self-hosting/image5.jpg
  public/_posts/_articles/marco-worms/self-hosting/image6.jpg
  public/_posts/_articles/marco-worms/self-hosting/image7.jpg
  public/_posts/_articles/marco-worms/self-hosting/image8.jpeg
  public/_posts/_articles/marco-worms/self-hosting/image9.jpg
Labels: article, English

#1243 [CMT-883-1243] translate(article): liquidity-mining-rewards-v2 - EL
  public/_posts/_articles/andre-cronje/liquidity-mining-rewards-v2/el.md
Labels: Greek, article

#1242 [CMT-882-1242] translate(article): why-audits-are-bad - EL
  public/_posts/_articles/andre-cronje/why-audits-are-bad/el.md
Labels: Greek, article

#1244 [CMT-884-1244] translate(article): ''The Blue Pill" - TR
  public/_posts/_articles/the-blue-pill/tr.md
Labels: Turkish, article

#1232 [CMT-875-1232] translate(financials): ''quarterly-report-2021-Q3" - TR
  public/_posts/_financials/quarterly-report/quarterly-report-2021-Q3/tr.md
Labels: Turkish, financials

#1237 [CMT-878-1237] edit(newsletters): Spanish translation review
  public/_posts/_newsletters/Yearn-Finance-Newsletter-44/es.md
  public/_posts/_newsletters/Yearn-Finance-Newsletter-47/es.md
  public/_posts/_newsletters/Yearn-Finance-Newsletter-53/es.md
  public/_posts/_newsletters/Yearn-Finance-Newsletter-54/es.md
  public/_posts/_newsletters/Yearn-Finance-Newsletter-55/es.md
Labels: Spanish, newsletters

#1241 [CMT-881-1241] translate(article): introducing-fixed-forex - EL
  public/_posts/_articles/andre-cronje/introducing-fixed-forex/el.md
Labels: Greek, article

#1236 [CMT-877-1236] Update es.md - The Blue Pill
  public/_posts/_articles/the-blue-pill/es.md
Labels: Spanish, article

#1275 [CMT-914-1275] translate(yearn-web-engineering-update-2022-01-17): PT
  public/_posts/_updates/web-team/yearn-web-engineering-update-2022-01-17/pt.md
Labels: Portuguese

#1274 [CMT-913-1274] Translation : yearn-comms/public/_posts/_tweets/what-is-a-DAO : ES
  public/_posts/_tweets/what-is-a-DAO/es.md
Labels: Spanish

#1273 [CMT-912-1273] Create hi.md
  public/_posts/_newsletters/Yearn-Finance-Newsletter-59/hi.md
Labels: Hindi

#1271 [CMT-910-1271] translate(tweet): risk-tooling-insight - ES
  public/_posts/_tweets/risk-tooling-insight/es.md
Labels: Spanish, tweets

#1268 [CMT-907-1268] translate(article): how-we-think-about-yearn - EL
  public/_posts/_articles/forum/how-we-think-about-yearn/el.md
Labels: Greek, article

#1267 [CMT-906-1267] translate(article): easily-earn-with-yearn-v2-in-argent - EL
  public/_posts/_articles/argent/el.md
Labels: Greek, article

#1256 [CMT-895-1256] translate(newsletter): YN59 - FR
  public/_posts/_newsletters/Yearn-Finance-Newsletter-59/fr.md
Labels: French, newsletters

#1264 [CMT-903-1264] translate(newsletter): YN59 - ES
  public/_posts/_newsletters/Yearn-Finance-Newsletter-59/es.md
Labels: Spanish

#1265 [CMT-904-1265] vi L10n for YN59
  public/_posts/_newsletters/Yearn-Finance-Newsletter-59/vi.md
Labels: Vietnamese

#1263 [CMT-902-1263] translation(newsletter): 52 - zh
  public/_posts/_newsletters/Yearn-Finance-Newsletter-52/zh.md
Labels: Chinese

#1257 [CMT-896-1257] translate(newsletter): YN59 - PT
  public/_posts/_newsletters/Yearn-Finance-Newsletter-59/pt.md
Labels: Portuguese, newsletters

#1253 [CMT-892-1253] translate(newsletter): YN59 - TR
  public/_posts/_newsletters/Yearn-Finance-Newsletter-59/tr.md
Labels: Turkish, newsletters

#1262 [CMT-901-1262] edit-fixed-forex-in-Chinese
  public/_posts/_articles/andre-cronje/introducing-fixed-forex/zh.md
Labels: fix

#1255 [CMT-894-1255] tranlate(newsletter): YN59 - EL
  public/_posts/_newsletters/Yearn-Finance-Newsletter-59/el.md
Labels: Greek, newsletters

#1269 [CMT-908-1269] translate(engineering): gnosis-safe - TR
  public/_posts/_updates/web-team/stealth-safe-guard-mev-protection-for-your-gnosis-safe/tr.md
Labels: Turkish, needs review by translator, engineering

#1228 [CMT-871-1228] translate(article): Yearn Finance explained - RU
  public/_posts/_articles/marco-worms/yearn-finance-explained-what-are-vaults-and-strategies/image1_ru.jpg
  public/_posts/_articles/marco-worms/yearn-finance-explained-what-are-vaults-and-strategies/image2_ru.jpg
  public/_posts/_articles/marco-worms/yearn-finance-explained-what-are-vaults-and-strategies/image3_ru.jpg
  public/_posts/_articles/marco-worms/yearn-finance-explained-what-are-vaults-and-strategies/ru.md
Labels: article, Russian

#1248 [CMT-888-1248] translate: (article) ''setup-notifications-tenderly'' to turkish
  public/_posts/_articles/marco-worms/setup-notifications-tenderly/tr.md
Labels: Turkish, article

#1254 [CMT-893-1254] translate(financials): quarterly-report-2021-Q3 - PT
  public/_posts/_financials/quarterly-report/quarterly-report-2021-Q3/pt.md
Labels: Portuguese, financials

#1247 [CMT-887-1247] translate(financials): quarterly-report-Q3-2021 - DE
  public/_posts/_financials/quarterly-report/quarterly-report-2021-Q3/de.md
Labels: German, financials

#1239 [CMT-879-1239] fair-launches-decentralized-collaboration-and-fixed-forex - Greek Translation
  public/_posts/_articles/andre-cronje/fair-launches-decentralized-collaboration-and-fixed-forex/el.md
Labels: Greek, article

#1249 [CMT-889-1249] translate(tweet): ''why-is-yearn-finance-built-different'' - TR
  public/_posts/_tweets/why-is-yearn-finance-built-different/en.md
  public/_posts/_tweets/why-is-yearn-finance-built-different/pt.md
  public/_posts/_tweets/why-is-yearn-finance-built-different/tr.md
Labels: Turkish, tweets

#1246 [CMT-886-1246] translate(article): the-blue-pill - HI
  public/_posts/_articles/the-blue-pill/hi.md
Labels: Hindi, article

#1245 [CMT-885-1245] translate(article): self-hosting-web3-services - HI
  public/_posts/_articles/marco-worms/self-hosting/hi.md
Labels: Hindi, article

#1276 add(article): People of Yearn : RestlessMik3 and J | yhelper
  public/_posts/_articles/people-of-yearn/Jyhelper/cover.jpg
  public/_posts/_articles/people-of-yearn/Jyhelper/en.md
  public/_posts/_articles/people-of-yearn/Jyhelper/image1.jpg
  public/_posts/_articles/people-of-yearn/RestlessMik3/cover.jpg
  public/_posts/_articles/people-of-yearn/RestlessMik3/en.md
  public/_posts/_articles/people-of-yearn/RestlessMik3/image1.jpg
Labels: English

#1261 [CMT-900-1261] fix(typo): yearn-metrics article ZH
  public/_posts/_articles/marco-worms/diving-into-yearn-metrics/zh.md
Labels: fix

#1270 [CMT-909-1270] translate(tweet): claim-from-old-ygov - ES
  public/_posts/_tweets/claim-from-old-ygov/es.md
Labels: Spanish

#1272 [CMT-911-1272] translate(tweet): what-can-you-do-in-a-DAO - ES
  public/_posts/_tweets/what-can-you-do-in-a-DAO/es.md
Labels: Spanish

#1279 [CMT-916-1279] translate-NL-59-in-Chinese
  public/_posts/_newsletters/Yearn-Finance-Newsletter-59/zh.md
Labels: Chinese

#1280 add(tweet): yearning-for-yearn - EN
  public/_posts/_tweets/Yearning-for-Yearn/en.md
  public/_posts/_tweets/Yearning-for-Yearn/image1.jpg
  public/_posts/_tweets/Yearning-for-Yearn/image2.jpg
  public/_posts/_tweets/Yearning-for-Yearn/image3.jpg
  public/_posts/_tweets/Yearning-for-Yearn/image4.jpg
Labels: English

#1282 [CMT-917-1282] fix: add missing link - YN60
  public/_posts/_newsletters/Yearn-Finance-Newsletter-60/en.md
Labels: English, fix

#1281 add(tweet): about-ERC-4626 - EN
  public/_posts/_tweets/ERC-4626s/en.md
  public/_posts/_tweets/ERC-4626s/image1.jpg
Labels: English

#1283 [CMT-918-1283] translate(newsletter): YN60 - EL
  public/_posts/_newsletters/Yearn-Finance-Newsletter-60/el.md
Labels: Greek

#1284 translate(newsletter): YN60 - FR
  public/_posts/_newsletters/Yearn-Finance-Newsletter-60/fr.md
Labels: newsletters

#1285 [CMT-919-1285] translate(newsletter): YN60 - TR
  public/_posts/_newsletters/Yearn-Finance-Newsletter-60/tr.md
Labels: Turkish

#1287 [CMT-921-1287] translate(newsletter): YN60 - PT
  public/_posts/_newsletters/Yearn-Finance-Newsletter-60/pt.md
Labels: Portuguese

#1288 [CMT-922-1288] translate(newsletter): YN60 - VI
  public/_posts/_newsletters/Yearn-Finance-Newsletter-60/vi.md
Labels: Vietnamese

#1290 [CMT-924-1290] review: YN60 - EL
  public/_posts/_newsletters/Yearn-Finance-Newsletter-60/el.md
Labels: Greek

#1289 [CMT-923-1289] translate(financials) Q3-2021-financial-report - VI
  public/_posts/_financials/quarterly-report/quarterly-report-2021-Q3/vi.md
Labels: Vietnamese

#1266 [CMT-905-1266] translate(newsletter): YN54 - HI
  public/_posts/_newsletters/Yearn-Finance-Newsletter-54/hi.md
Labels: Hindi, newsletters, needs review by translator

#1293 [CMT-926-1293] translate(newsletter): YN60 - ZH
  public/_posts/_newsletters/Yearn-Finance-Newsletter-60/zh.md
Labels: Chinese

#1292 [CMT-925-1292] translate(tweet): yearning-for-yearn - PT
  public/_posts/_tweets/Yearning-for-Yearn/pt.md
Labels: Portuguese

#1286 [CMT-920-1286] translate(newsletter): YN60 - ES
  public/_posts/_newsletters/Yearn-Finance-Newsletter-60/es.md
Labels: Spanish, needs review by translator

#1296 [CMT-929-1296] translate(article): self-hosting - PT
  public/_posts/_articles/marco-worms/self-hosting/pt.md
Labels: Portuguese

#1294 [CMT-927-1294] translate(article): my-first-impressions-at-yearn - EL
  public/_posts/_articles/kish/my-first-impressions-at-yearn/el.md
Labels: Greek

#1300 [CMT-933-1300] TLcheck(article): yearn-partners - ZH
  public/_posts/_articles/marco-worms/yearn-partners/zh.md
Labels: Chinese

#1301 [CMT-934-1301] TLcheck(newsletter): YN52 - ZH
  public/_posts/_newsletters/Yearn-Finance-Newsletter-52/zh.md
Labels: Chinese

#1302 add(article): yearn-governance-explained - EN
  public/_posts/_articles/marco-worms/yearn-governance/en.md
  public/_posts/_articles/marco-worms/yearn-governance/image1.jpg
  public/_posts/_articles/marco-worms/yearn-governance/image2.jpg
  public/_posts/_articles/marco-worms/yearn-governance/image3.jpg
  public/_posts/_articles/marco-worms/yearn-governance/image4.jpg
  public/_posts/_articles/marco-worms/yearn-governance/image5.jpg
Labels: English

#1309 [CMT-940-1309] translate(newsletter): YN59 - DE
  public/_posts/_newsletters/Yearn-Finance-Newsletter-59/de.md
Labels: German

#1304 translate(article): yearn-governance - FR
  public/_posts/_articles/marco-worms/yearn-governance/fr.md
Labels: French

#1311 [CMT-942-1311] translate(article): how-yearn-vault-strategies-are-endorsed - EL
  public/_posts/_articles/marco-worms/how-new-yearn-vault-strategies-are-endorsed/el.md
Labels: Greek

#1295 [CMT-928-1295] translate(engineering): stealth-safe-guard-mev-protection-for-your-gnosis-safe - ES
  public/_posts/_updates/web-team/stealth-safe-guard-mev-protection-for-your-gnosis-safe/es.md
Labels: Spanish

#1307 [CMT-938-1307] fix:(tweet): what-is-a-DAO - ES
  public/_posts/_tweets/what-is-a-DAO/es.md
Labels: Spanish

#1298 [CMT-931-1298] translate(engineering): yearn-web-engineering-update-2022-01-10 - ES
  public/_posts/_updates/web-team/yearn-web-engineering-update-2022-01-10/es.md
Labels: Spanish

#1306 [CMT-937-1306] Changes on how Abracadabra works
  public/_posts/_articles/marco-worms/yearn-partners/en.md
Labels: English

#1303 [CMT-935-1303] translate(article): yearn-partners - ES
  public/_posts/_articles/marco-worms/yearn-partners/es.md
Labels: Spanish

#1315 [CMT-946-1315] add(newsletter): YN61 - EN
  public/_posts/_newsletters/Yearn-Finance-Newsletter-61/cover.jpg
  public/_posts/_newsletters/Yearn-Finance-Newsletter-61/en.md
  public/_posts/_newsletters/Yearn-Finance-Newsletter-61/image1.jpg
  public/_posts/_newsletters/Yearn-Finance-Newsletter-61/image2.jpg
  public/_posts/_newsletters/Yearn-Finance-Newsletter-61/image3.jpg
  public/_posts/_newsletters/Yearn-Finance-Newsletter-61/image4.jpg
  public/_posts/_newsletters/Yearn-Finance-Newsletter-61/image5.jpg
  public/_posts/_newsletters/Yearn-Finance-Newsletter-61/image6.jpg
Labels: newsletters, English

#1316 [CMT-947-1316] fix: broken img links, typos
  public/_posts/_newsletters/Yearn-Finance-Newsletter-61/en.md
Labels: English

#1317 [CMT-948-1317] translate(newsletter): YN61 - TR
  public/_posts/_newsletters/Yearn-Finance-Newsletter-61/tr.md
Labels: Turkish

#1297 [CMT-930-1297] translate(engineering): yearn-web-engineering-update-2022-01-03 - ES
  public/_posts/_updates/web-team/yearn-web-engineering-update-2022-01-03/es.md
Labels: Spanish, needs review by translator

#1308 [CMT-939-1308] translate(article): what-are-vaults-and-strategies - ES
  public/_posts/_articles/marco-worms/yearn-finance-explained-what-are-vaults-and-strategies/es.md
Labels: Spanish, needs review by translator

#1310 [CMT-941-1310] translate(engineering): yearn-web-engineering-update-2022-01-31 - ES
  public/_posts/_updates/web-team/yearn-web-engineering-update-2022-01-31/es.md
Labels: Spanish, needs review by translator

#1313 [CMT-944-1313] translate(engineering): yearn-web-engineering-update-2022-01-17 - ES
  public/_posts/_updates/web-team/yearn-web-engineering-update-2022-01-17/es.md
Labels: Spanish, needs review by translator

#1324 add french version for [Newsletter] 61
  public/_posts/_newsletters/Yearn-Finance-Newsletter-61/fr.md
Labels: French

#1322 [CMT-953-1322] translate(Yearn-Finance-Newsletter-61): PT
  public/_posts/_newsletters/Yearn-Finance-Newsletter-61/pt.md
Labels: Portuguese

#1320 [CMT-951-1320] Yearn Finance NL#61 Greek Translation
  public/_posts/_newsletters/Yearn-Finance-Newsletter-61/el.md
Labels: Greek

#1326 [CMT-955-1326] translate(newsletter): YN61 - ZH
  public/_posts/_newsletters/Yearn-Finance-Newsletter-61/zh.md
Labels: Chinese

#1328 [CMT-957-1328] translate(article): yearn-governance - HI
  public/_posts/_articles/marco-worms/yearn-governance/hi.md
Labels: Hindi
