Repository yearn/yearn-comms, pull requests merged in 2022-02, with the labels that each got.

#988 [CMT-656-988] Update 2021-06-01-Yearn's-Dai-Vault.md - Spanish - RM3
  Articles/_posts/Medium/Wot Is Goin On/Yearn's Dai Vault/2021-06-01-Yearn's-Dai-Vault.md
Labels: Spanish

#987 [CMT-153] Article - Yearn Finance - Decentralised Asset - German
  Articles/_posts/SEBA Bank/Yearn-Finance-Decentralised-Asset-Management/2021-06-02-Yearn-Finance-Decentralised-Asset-Management.md
Labels: German

#986 [CMT-655-986] Yearn Finance Newsletter #55 German translation
  Newsletters/_posts/Yearn-Finance-Newsletter-55/2022-01-26-Yearn-Finance-Newsletter-55.md
Labels: German

#981 [CMT-651-981] Update 2021-04-07-Can-Yearn-Disrupt-the-110-Trillion-Asset-Management…Spanish RM3
  Articles/_posts/Medium/Wot Is Goin On/Can Yearn Disrupt/2021-04-07-Can-Yearn-Disrupt-the-110-Trillion-Asset-Management-Industry.md
Labels: translation check, Spanish

#980 [CMT-650-980] translation(newsletter): Yearn Finance Newsletter #55
  Newsletters/_posts/Yearn-Finance-Newsletter-55/2022-01-26-Yearn-Finance-Newsletter-55.md
Labels: Japanese

#972 [CMT-646-972] Update 2022-01-26-Yearn-Finance-Newsletter-55.md
  Newsletters/_posts/Yearn-Finance-Newsletter-55/2022-01-26-Yearn-Finance-Newsletter-55.md
Labels: Portuguese

#965 [CMT-639-965] Yearn finance newsletter 55
  Newsletters/_posts/Yearn-Finance-Newsletter-55/2022-01-26-Yearn-Finance-Newsletter-55.md
Labels: Chinese

#944 [CMT-618-944] Update 2022-01-26-Yearn-Finance-Newsletter-55.md Spanish - RM3
  Newsletters/_posts/Yearn-Finance-Newsletter-55/2022-01-26-Yearn-Finance-Newsletter-55.md
Labels: Spanish, needs review by translator

#945 [CMT-619-945] Yearn Finance Newsletter #55 Greek translation
  Newsletters/_posts/Yearn-Finance-Newsletter-55/2022-01-26-Yearn-Finance-Newsletter-55.md
Labels: translation check, Greek

#919 [CMT-610-919] Update 2022-01-20-Yearn-Finance-Newsletter-54.md Spanish RM3
  Newsletters/_posts/Yearn-Finance-Newsletter-54/2022-01-20-Yearn-Finance-Newsletter-54.md
Labels: Spanish, needs review by translator

#920 [CMT-611-920] Yearn Finance Newsletter #54 Greek Translation
  Newsletters/_posts/Yearn-Finance-Newsletter-54/2022-01-20-Yearn-Finance-Newsletter-54.md
Labels: translation check, Greek

#998 add [Newsletter] 57
  public/_posts/_newsletters/Yearn-Finance-Newsletter-57/en.md
  public/_posts/_newsletters/Yearn-Finance-Newsletter-57/image1.jpg
  public/_posts/_newsletters/Yearn-Finance-Newsletter-57/image2.jpg
  public/_posts/_newsletters/Yearn-Finance-Newsletter-57/image3.jpg
  public/_posts/_newsletters/Yearn-Finance-Newsletter-57/image4.jpg
  public/_posts/_newsletters/Yearn-Finance-Newsletter-57/image5.jpg
  public/_posts/_newsletters/Yearn-Finance-Newsletter-57/image6.jpg
Labels: article, English

#1001 [CMT-666-1001] translation(newsletter): 53 - pt
  public/_posts/_newsletters/Yearn-Finance-Newsletter-53/de.md
  public/_posts/_newsletters/Yearn-Finance-Newsletter-53/el.md
  public/_posts/_newsletters/Yearn-Finance-Newsletter-53/en.md
  public/_posts/_newsletters/Yearn-Finance-Newsletter-53/fr.md
  public/_posts/_newsletters/Yearn-Finance-Newsletter-53/pt.md
Labels: Portuguese

#1014 [CMT-677-1014] translation(newsletter): 56 -es -restlessmike
  public/_posts/_newsletters/Yearn-Finance-Newsletter-56/es.md
Labels: Spanish
