Repository yearn/yearn-comms, pull requests merged in 2022-05, with the labels that each got.

#1355 [CMT-982-1355] feat: add support for Plausible analytics
  pages/_app.js
Labels: enhancement, blog

#1331 add(article): people-of-yearn-marco-worms - EN
  public/_posts/_articles/people-of-yearn/marcos-worm/cover.jpg
  public/_posts/_articles/people-of-yearn/marcos-worm/en.md
  public/_posts/_articles/people-of-yearn/marcos-worm/image2.jpg
  public/_posts/_articles/people-of-yearn/marcos-worm/image3.jpg
Labels: English

#1335 add(article): yearn-vaults-v3 - EN
  public/_posts/_articles/marco-worms/yearn-v3/en.md
  public/_posts/_articles/marco-worms/yearn-v3/image1.jpg
  public/_posts/_articles/marco-worms/yearn-v3/image2.jpg
Labels: English

#1354 [CMT-981-1354] feat: add "people-of-yearn" "farrahmay" & "transcriptions" subfolder support
  pages/[path]/[...slug].js
  pages/[path]/index.js
  pages/index.js
  public/_posts/_articles/farrahmay/.gitkeep
  public/_posts/_articles/transcriptions/.gitkeep
Labels: enhancement, blog

#1387 [CMT-1011-1387] add(article): yearn-allowlist - EN
  public/_posts/_updates/yearn-allowlist/en.md
  public/_posts/_updates/yearn-allowlist/image1.jpg
Labels: English

#1336 [CMT-963-1336] translate(german): YN61 (newsletter)
  public/_posts/_newsletters/Yearn-Finance-Newsletter-61/de.md
Labels: German

#1329 [CMT-958-1329] translate(newsletter): YN61 - VI
  public/_posts/_newsletters/Yearn-Finance-Newsletter-61/vi.md
Labels: Vietnamese

#1373 [CMT-997-1373] translate(turkish): people-of-yearn-marco-worms (article)
  public/_posts/_articles/people-of-yearn/marcos-worm/tr.md
Labels: Turkish

#1381 [CMT-1005-1381] translate(portuguese): people-of-yearn-marco-worms (article)
  public/_posts/_articles/people-of-yearn/marcos-worm/pt.md
Labels: Portuguese

#1378 [CMT-1002-1378] translate(french): people-of-yearn-marco-worms (article)
  public/_posts/_articles/people-of-yearn/marcos-worm/fr.md
Labels: French

#1366 [CMT-992-1366] translate(spanish): people-of-yearn-marco-worms (article)
  public/_posts/_articles/people-of-yearn/marcos-worm/es.md
Labels: Spanish

#1334 [CMT-962-1334] translate(spanish): people-of-yearn-RestlessMik3 (article)
  public/_posts/_articles/people-of-yearn/RestlessMik3/es.md
Labels: Spanish

#1375 [CMT-999-1375] translate(portuguese): people-of-yearn-RestlessMik3 (article)
  public/_posts/_articles/people-of-yearn/RestlessMik3/pt.md
Labels: Portuguese

#1376 [CMT-1000-1376] translate(turkish): people-of-yearn-RestlessMik3 (article)
  public/_posts/_articles/people-of-yearn/RestlessMik3/tr.md
Labels: Turkish

#1372 [CMT-996-1372] translate(portuguese): people-of-yearn-Jyhelper (article)
  public/_posts/_articles/people-of-yearn/Jyhelper/pt.md
Labels: Portuguese

#1333 [CMT-961-1333] translate(spanish): people-of-yearn-Jyhelper (article)
  public/_posts/_articles/people-of-yearn/Jyhelper/es.md
Labels: Spanish

#1349 [CMT-976-1349] translate(chinese): ERC4626s (tweet)
  public/_posts/_tweets/ERC-4626s/zh.md
Labels: Chinese

#1385 [CMT-1009-1385] translate(portuguese): ERC-4626s (tweet)
  public/_posts/_tweets/ERC-4626s/pt.md
Labels: Portuguese

#1361 [CMT-988-1361] translate(turkish): ERC4626s (tweet)
  public/_posts/_tweets/ERC-4626s/tr.md
Labels: Turkish

#1332 [CMT-960-1332] translate(chinese): yearn-governance (article)
  public/_posts/_articles/marco-worms/yearn-governance/zh.md
Labels: Chinese

#1356 [CMT-983-1356] translate(turkish): yearn-governance (article)
  public/_posts/_articles/marco-worms/yearn-governance/tr.md
Labels: Turkish

#1404 [CMT-1025-1404] fix(typo): replace line - eth address
  public/_posts/_updates/yearn-allowlist/en.md
Labels: fix

#1405 [CMT-1026-1405] add(english+french): yearn-wants-to-buy-your-YFI (article)
  public/_posts/_articles/yearn-finance/yearn-wants-to-buy-your-YFI/cover.jpg
  public/_posts/_articles/yearn-finance/yearn-wants-to-buy-your-YFI/en.md
  public/_posts/_articles/yearn-finance/yearn-wants-to-buy-your-YFI/fr.md
Labels: French, English

#1401 [CMT-1022-1401] feat: add html support for markdown
  components/TemplateArticle.js
  package.json
  pages/_app.js
  pages/_document.js
  style/Default.css
  yarn.lock
Labels: enhancement

#1416 [CMT-1037-1416] translate(spanish): yearn-wants-to-buy-your-YFI (article)
  public/_posts/_articles/yearn-finance/yearn-wants-to-buy-your-YFI/es.md
Labels: Spanish

#1415 [CMT-1036-1415] translate(turkish): yearn-wants-to-buy-your-YFI (article)
  public/_posts/_articles/yearn-finance/yearn-wants-to-buy-your-YFI/tr.md
Labels: Turkish

#1407 [CMT-1028-1407] translate(portuguese): yearn-allowlist (engineering)
  public/_posts/_updates/yearn-allowlist/pt.md
Labels: Portuguese

#1403 [CMT-1024-1403] translate(spanish): yearn-allowlist (engineering)
  public/_posts/_updates/yearn-allowlist/es.md
Labels: Spanish

#1389 [CMT-1013-1389] translate(turkish): yearn-allowlist (engineering)
  public/_posts/_updates/yearn-allowlist/tr.md
Labels: Turkish

#1397 [CMT-1021-1397] translate(chinese): yearn-allowlist (engineering)
  public/_posts/_updates/yearn-allowlist/zh.md
Labels: Chinese

#1410 [CMT-1031-1410] translate(greek): yearn-allowlist (engineering)
  public/_posts/_updates/yearn-allowlist/el.md
Labels: Greek

#1417 [CMT-1038-1417] translate(chinese): yearn-wants-to-buy-your-YFI (article)
  public/_posts/_articles/yearn-finance/yearn-wants-to-buy-your-YFI/zh.md
Labels: Chinese

#1350 [CMT-977-1350] translate(german): clarifying-2020-merger (article)
  public/_posts/_articles/yearn-finance/clarifying-2020-mergers/de.md
Labels: German

#1377 [CMT-1001-1377] translate(german): yearn-partners (article)
  public/_posts/_articles/marco-worms/yearn-partners/de.md
Labels: German

#1370 [CMT-994-1370] translate(portuguese): yearn-governance (article)
  public/_posts/_articles/marco-worms/yearn-governance/pt.md
Labels: Portuguese

#1388 [CMT-1012-1388] tl-check(chinese): YN61 (newsletter)
  public/_posts/_newsletters/Yearn-Finance-Newsletter-61/zh.md
Labels: Chinese

#1419 [CMT-1040-1419] translate(spanish): yearn-at-eth-amsterdam (article)
  public/_posts/_articles/farrahmay/yearn-at-eth-amsterdam/es.md
Labels: Spanish

#1360 [CMT-987-1360] translate(turkish): yearn-v3 (article)
  public/_posts/_articles/marco-worms/yearn-v3/en.md
  public/_posts/_articles/marco-worms/yearn-v3/tr.md
Labels: Turkish

#1364 translate(french): yearn-v3 (article)
  public/_posts/_articles/marco-worms/yearn-v3/fr.md
Labels: French

#1369 [CMT-993-1369] translate(spanish): yearn-v3 (article)
  public/_posts/_articles/marco-worms/yearn-v3/es.md
Labels: Spanish

#1371 [CMT-995-1371] translate(portuguese): yearn-v3 (article)
  public/_posts/_articles/marco-worms/yearn-v3/pt.md
Labels: Portuguese

#1374 [CMT-998-1374] translate(chinese): yearn-v3 (article)
  public/_posts/_articles/marco-worms/yearn-v3/zh.md
Labels: Chinese

#1409 [CMT-1030-1409] translate(german): yearn-v3 (article)
  public/_posts/_articles/marco-worms/yearn-v3/de.md
Labels: German

#1359 [CMT-986-1359] translate(turkish): web-engineering-update-2022-02-28 (engineering)
  public/_posts/_updates/web-team/yearn-web-engineering-update-2022-02-28/tr.md
Labels: Turkish

#1384 [CMT-1008-1384] translate(portuguese): yearn-web-engineering-update-2022-02-28 (engineering)
  public/_posts/_updates/web-team/yearn-web-engineering-update-2022-02-28/pt.md
Labels: Portuguese

#1414 [CMT-1035-1414] translate(spanish): yearn-web-engineering-update-2022-02-28 (engineering)
  public/_posts/_updates/web-team/yearn-web-engineering-update-2022-02-28/es.md
Labels: Spanish

#1357 [CMT-984-1357] translate(turkish): web-engineering-update-2022-03-14 (engineering)
  public/_posts/_updates/web-team/yearn-web-engineering-update-2022-03-14/tr.md
Labels: Turkish

#1358 [CMT-985-1358] translate(turkish): web-engineering-update-2022-03-07 (engineering)
  public/_posts/_updates/web-team/yearn-web-engineering-update-2022-03-07/tr.md
Labels: Turkish

#1215 [CMT-859-1215] translate(german): diving-into-yearn-metrics (article)
  public/_posts/_articles/marco-worms/diving-into-yearn-metrics/de.md
Labels: German

#1422 [CMT-1043-1422] translate(french): ERC-4626s (tweet)
  public/_posts/_tweets/ERC-4626s/fr.md
Labels: French

#1352 [CMT-979-1352] translate(chinese): yearning-for-yearn (tweet)
  public/_posts/_tweets/Yearning-for-Yearn/zh.md
Labels: Chinese

#1362 [CMT-989-1362] translate(turkish): yearning-for-yearn (tweet)
  public/_posts/_tweets/Yearning-for-Yearn/tr.md
Labels: Turkish

#1411 [CMT-1032-1411] translate(chinese): what-can-you-do-in-a-DAO (tweet)
  public/_posts/_tweets/what-can-you-do-in-a-DAO/en.md
  public/_posts/_tweets/what-can-you-do-in-a-DAO/zh.md
Labels: Chinese

#1337 [CMT-964-1337] translate(spanish): yvboost (article)
  public/_posts/_articles/yearn-finance/yvboost/de.md
  public/_posts/_articles/yearn-finance/yvboost/en.md
  public/_posts/_articles/yearn-finance/yvboost/es.md
  public/_posts/_articles/yearn-finance/yvboost/fr.md
  public/_posts/_articles/yearn-finance/yvboost/hi.md
  public/_posts/_articles/yearn-finance/yvboost/ja.md
  public/_posts/_articles/yearn-finance/yvboost/pt.md
  public/_posts/_articles/yearn-finance/yvboost/tr.md
  public/_posts/_articles/yearn-finance/yvboost/vi.md
  public/_posts/_articles/yearn-finance/yvboost/zh.md
Labels: Spanish

#1424 [CMT-1045-1424] add(english): people-of-yearn-corn (article)
  public/_posts/_articles/people-of-yearn/corn/cover.jpg
  public/_posts/_articles/people-of-yearn/corn/en.md
  public/_posts/_articles/people-of-yearn/corn/image1.jpg
  public/_posts/_articles/people-of-yearn/corn/image2.jpg
Labels: English

#1353 [CMT-980-1353] translate(german): setup-tenderly-notifications (article)
  public/_posts/_articles/marco-worms/setup-notifications-tenderly/de.md
Labels: German

#1412 [CMT-1033-1412] translate(turkish): engineering updates - 21 feb
  public/_posts/_updates/web-team/yearn-web-engineering-update-2022-02-21/tr.md
Labels: Turkish

#1413 [CMT-1034-1413] translate(turkish): engineering update - 31jan
  public/_posts/_updates/web-team/yearn-web-engineering-update-2022-01-31/tr.md
Labels: Turkish

#1365 [CMT-991-1365] translate(spanish): YN45 (newsletter)
  public/_posts/_newsletters/Yearn-Finance-Newsletter-45/es.md
Labels: Spanish

#1406 [CMT-1027-1406] translate(portuguese): how-to-contribute-to-daos (transcription)
  public/_posts/_articles/transcriptions/.gitkeep
  public/_posts/_articles/transcriptions/how-to-contribute-to-daos/en.md
  public/_posts/_articles/transcriptions/how-to-contribute-to-daos/pt.md
Labels: Portuguese

#1386 [CMT-1010-1386] translate(turkish): how-to-contribute-to-daos (transcriptions)
  public/_posts/_articles/transcriptions/how-to-contribute-to-daos/tr.md
Labels: Turkish

#1363 [CMT-990-1363] translate(greek): the-blue-pill (article)
  public/_posts/_articles/the-blue-pill/el.md
Labels: Greek

#1423 [CMT-1044-1423] translate(turkish): yearn-at-eth-amsterdam (article)
  public/_posts/_articles/farrahmay/.gitkeep
  public/_posts/_articles/farrahmay/yearn-at-eth-amsterdam/tr.md
Labels: Turkish

#1421 [CMT-1042-1421] translate(spanish): self-hosting-web3-services (article)
  public/_posts/_articles/marco-worms/self-hosting/en.md
  public/_posts/_articles/marco-worms/self-hosting/es.md
  public/_posts/_articles/marco-worms/self-hosting/fr.md
  public/_posts/_articles/marco-worms/self-hosting/hi.md
  public/_posts/_articles/marco-worms/self-hosting/pt.md
  public/_posts/_articles/marco-worms/self-hosting/tr.md
  public/_posts/_articles/marco-worms/self-hosting/zh.md
Labels: Spanish

#1408 [CMT-1029-1408] translate(spanish) : web-engineering-update-2022-02-21 (engineering)
  public/_posts/_updates/web-team/yearn-web-engineering-update-2022-02-21/en.md
  public/_posts/_updates/web-team/yearn-web-engineering-update-2022-02-21/es.md
Labels: Spanish

#1418 [CMT-1039-1418] TLcheck(chinese): yearn-allowlist (article)
  public/_posts/_updates/yearn-allowlist/zh.md
Labels: Chinese, fix

#1398 [CMT-1018-1394] add(english): hacking-with-yearn (article)
  public/_posts/_articles/farrahmay/hacking-with-yearn/cover.jpg
  public/_posts/_articles/farrahmay/hacking-with-yearn/en.md
  public/_posts/_articles/farrahmay/hacking-with-yearn/image1.jpg
  public/_posts/_articles/farrahmay/hacking-with-yearn/image2.jpg
  public/_posts/_articles/farrahmay/hacking-with-yearn/image3.jpg
  public/_posts/_articles/farrahmay/hacking-with-yearn/image4.jpg
Labels: English

#1431 [CMT-1052-1431] add(english): YN62 (newsletter)
  public/_posts/_newsletters/Yearn-Finance-Newsletter-62/cover.jpg
  public/_posts/_newsletters/Yearn-Finance-Newsletter-62/en.md
  public/_posts/_newsletters/Yearn-Finance-Newsletter-62/image1.jpg
  public/_posts/_newsletters/Yearn-Finance-Newsletter-62/image2.jpg
  public/_posts/_newsletters/Yearn-Finance-Newsletter-62/image3.jpg
  public/_posts/_newsletters/Yearn-Finance-Newsletter-62/image4.jpg
  public/_posts/_newsletters/Yearn-Finance-Newsletter-62/image5.jpg
  public/_posts/_newsletters/Yearn-Finance-Newsletter-62/image6.jpg
Labels: English

#1443 [CMT-1064-1443] YN #62 German Translation
  public/_posts/_newsletters/Yearn-Finance-Newsletter-62/de.md
Labels: German

#1437 [CMT-1058-1437] translate(hindi): marco-worms/yearn-v3
  public/_posts/_articles/marco-worms/diving-into-yearn-metrics/hi.md
  public/_posts/_articles/marco-worms/yearn-v3/hi.md
Labels: Hindi

#1436 [CMT-1057-1436] translate(article): hacking-with-yearn : ES
  public/_posts/_articles/farrahmay/hacking-with-yearn/es.md
Labels: Spanish

#1435 [CMT-1056-1435] translate(Portuguese): hacking-with-yearn(article)
  public/_posts/_articles/farrahmay/hacking-with-yearn/pt.md
Labels: Portuguese

#1434 [CMT-1055-1434] Create hi.md
  public/_posts/_articles/yearn-finance/yearn-wants-to-buy-your-YFI/hi.md
  public/_posts/_newsletters/Yearn-Finance-Newsletter-57/hi.md
  public/_posts/_newsletters/Yearn-Finance-Newsletter-61/hi.md
Labels: Hindi

#1432 [CMT-1053-1432] translate(portuguese): Yearn-Finance-Newsletter-62(newsletter)
  public/_posts/_newsletters/Yearn-Finance-Newsletter-62/pt.md
Labels: Portuguese
