Repository yearn/yearn-comms, pull requests merged in 2022-01, with the labels that each got.

#761 [CMT-469-761] Add en YN50 + images
  Newsletters/_posts/Yearn-Finance-Newsletter-50/2021-12-05-Yearn-Finance-Newsletter-50.md
  Newsletters/_posts/Yearn-Finance-Newsletter-50/image1.png
  Newsletters/_posts/Yearn-Finance-Newsletter-50/image2.png
  Newsletters/_posts/Yearn-Finance-Newsletter-50/image3.png
  Newsletters/_posts/Yearn-Finance-Newsletter-50/image4.png
Labels: English

#786 Create Yearn-Finance-Newsletter-51.md + images
  Newsletters/_posts/Yearn-Finance-Newsletter-51/Yearn-Finance-Newsletter-51.md
  Newsletters/_posts/Yearn-Finance-Newsletter-51/image1.png
  Newsletters/_posts/Yearn-Finance-Newsletter-51/image2.png
  Newsletters/_posts/Yearn-Finance-Newsletter-51/image3.png
  Newsletters/_posts/Yearn-Finance-Newsletter-51/image4.png
  Newsletters/_posts/Yearn-Finance-Newsletter-51/image5.png
Labels: English

#792 [CMT-493-792] Create Yearn-Finance-Newsletter-52.md + images
  Newsletters/_posts/Yearn-Finance-Newsletter-52/Yearn-Finance-Newsletter-52.md
  Newsletters/_posts/Yearn-Finance-Newsletter-52/image1.png
  Newsletters/_posts/Yearn-Finance-Newsletter-52/image2.png
  Newsletters/_posts/Yearn-Finance-Newsletter-52/image3.png
  Newsletters/_posts/Yearn-Finance-Newsletter-52/image4.png
Labels: English

#802 [Newsletter] Newsletter 52- 51 and 50 [French]
  Newsletters/_posts/Yearn-Finance-Newsletter-50/2021-12-05-Yearn-Finance-Newsletter-50.md
  Newsletters/_posts/Yearn-Finance-Newsletter-51/2021-12-22-Yearn-Finance-Newsletter-51.md
  Newsletters/_posts/Yearn-Finance-Newsletter-52/2022-01-02-Yearn-Finance-Newsletter-52.md
Labels: needs review by translator

#812 [CMT-510-812] Add docker for easier deployment locally
  README.md
  _config.docker.yml
  docker-compose.yml
Labels: enhancement

#829 [CMT-526-829] Update 2022-01-02-Yearn-Finance-Newsletter-52.md
  Newsletters/_posts/Yearn-Finance-Newsletter-52/2022-01-02-Yearn-Finance-Newsletter-52.md
Labels: Portuguese

#860 [CMT-552-860] Update 2022-01-11-Yearn-Finance-Newsletter-53.md RM3
  Newsletters/_posts/Yearn-Finance-Newsletter-53/2022-01-11-Yearn-Finance-Newsletter-53.md
Labels: Spanish, needs review by translator

#833 Yearn-Finance-Newsletter-52 - TR
  Newsletters/_posts/Yearn-Finance-Newsletter-52/2022-01-02-Yearn-Finance-Newsletter-52.md
Labels: Turkish, needs review by translator

#810 [CMT-508-810] Yearn-Finance-Newsletter-50 - TR
  Newsletters/_posts/Yearn-Finance-Newsletter-50/2021-12-05-Yearn-Finance-Newsletter-50.md
Labels: Turkish

#852 [CMT-545-852] Update 2021-03-31-Decentralized-Payroll-Management-for-DAOs.md RM3
  Articles/_posts/Medium/Andre Cronje/Decentralized Payroll Management for DAOs/2021-03-31-Decentralized-Payroll-Management-for-DAOs.md
Labels: Spanish

#916 [CMT-607-916] translate(tweet): what is a dao
  Tweets/_posts/What is a DAO/2021-06-30-What-is-a-DAO.md
Labels: Greek

#921 [CMT-612-921] YN54 Translated to Chinese
  Newsletters/_posts/Yearn-Finance-Newsletter-54/2022-01-20-Yearn-Finance-Newsletter-54.md
Labels: Chinese, needs review by translator

#923 translation(newsletter) : Yearn Finance newsletter #54
  Newsletters/_posts/Yearn-Finance-Newsletter-54/2022-01-20-Yearn-Finance-Newsletter-54.md
Labels: help wanted, Japanese
